/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glyph_kas;

import javax.swing.JOptionPane;

/**
 *
 * @author auralintang
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minggu = new javax.swing.JComboBox<>();
        bulan = new javax.swing.JComboBox<>();
        hbulan = new javax.swing.JTextField();
        hminggu = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        hsaldo = new javax.swing.JTextField();
        btnInfo = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minggu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minggu1", "Minggu2", "Minggu3", "Minggu4", "Minggu5" }));
        minggu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mingguActionPerformed(evt);
            }
        });
        getContentPane().add(minggu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 30));

        bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "July", "Agustus", "September", "Oktober", "November", "Desember", "Januari", "Februari", "Maret", "April", "Mei", "Juni" }));
        bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanActionPerformed(evt);
            }
        });
        getContentPane().add(bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 100, 30));

        hbulan.setEditable(false);
        getContentPane().add(hbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 150, 30));

        hminggu.setEditable(false);
        hminggu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmingguActionPerformed(evt);
            }
        });
        getContentPane().add(hminggu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 30));

        btnBayar.setText("BAYAR");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 250, 40));

        jTextField1.setEditable(false);
        jTextField1.setText("SALDO :");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, 30));

        hsaldo.setEditable(false);
        hsaldo.setText("0");
        getContentPane().add(hsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, 30));

        btnInfo.setText("INFO");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 120, 30));

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 170, 130, 30));

        setSize(new java.awt.Dimension(372, 266));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mingguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mingguActionPerformed
        // TODO add your handling code here:
        if(minggu.getSelectedItem().equals("Minggu1")){
            hminggu.setText("2000");
        }
        else if(minggu.getSelectedItem().equals("Minggu2")){
            hminggu.setText("4000");
        }
        else if(minggu.getSelectedItem().equals("Minggu3")){
            hminggu.setText("6000");
        }
        else if(minggu.getSelectedItem().equals("Minggu4")){
            hminggu.setText("8000");
        }
        else if(minggu.getSelectedItem().equals("Minggu5")){
            hminggu.setText("10000");
        }
    }//GEN-LAST:event_mingguActionPerformed

    private void bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanActionPerformed
        // TODO add your handling code here:
        if(bulan.getSelectedItem().equals("July")){
            hbulan.setText("1");
        }
        else if(bulan.getSelectedItem().equals("Agustus")){
            hbulan.setText("2");
        }
        else if(bulan.getSelectedItem().equals("September")){
            hbulan.setText("3");
        }
        else if(bulan.getSelectedItem().equals("Oktober")){
            hbulan.setText("4");
        }
        else if(bulan.getSelectedItem().equals("November")){
            hbulan.setText("5");
        }
        else if(bulan.getSelectedItem().equals("Desember")){
            hbulan.setText("6");
        }
        else if(bulan.getSelectedItem().equals("Januari")){
            hbulan.setText("7");
        }
        else if(bulan.getSelectedItem().equals("Februari")){
            hbulan.setText("8");
        }
        else if(bulan.getSelectedItem().equals("Maret")){
            hbulan.setText("9");
        }
        else if(bulan.getSelectedItem().equals("April")){
            hbulan.setText("10");
        }
        else if(bulan.getSelectedItem().equals("Mei")){
            hbulan.setText("11");
        }
        else if(bulan.getSelectedItem().equals("Juni")){
            hbulan.setText("12");
        }

    }//GEN-LAST:event_bulanActionPerformed

    private void hmingguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmingguActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_hmingguActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        String bln = hbulan.getText();
        String mng = hminggu.getText();
        String sld = hsaldo.getText();
        boolean huruf = false;
        int b = 0;
        int m = 0;
        int s = 0;
        float num1;
        float num2;

        try {
            num1 = Float.parseFloat(bln);
            num2 = Float.parseFloat(mng);
        }
        catch (NumberFormatException e) {
            huruf = true;
        }

        if (huruf) {
            JOptionPane.showMessageDialog(null, "Data diisi dengan Angka");
            b = Integer.parseInt(bln);
            m = Integer.parseInt(mng);
            s = Integer.parseInt(sld);
        }

        else{

            int b1 = Integer.parseInt(hbulan.getText());
            int m1 = Integer.parseInt(hminggu.getText());
            int s2 = Integer.parseInt(hsaldo.getText());
            int x = b1*m1+s2;

            hsaldo.setText(String.valueOf(x));
        }
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        info i;
        i = new info();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        keluar k;
        k = new keluar();
        k.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JComboBox<String> bulan;
    private javax.swing.JTextField hbulan;
    private javax.swing.JTextField hminggu;
    private javax.swing.JTextField hsaldo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> minggu;
    // End of variables declaration//GEN-END:variables
}
